version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1212
      POSTGRES_USER: postgres
      POSTGRES_DB: seleccion_apec
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "9000:9000"